name: aimeetup-postgres-db
services:
  db:
    container_name: postgres-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ai_news
      - POSTGRES_PASSWORD=Dgp@080405
      - POSTGRES_DB=ai_news
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: